### ISSUE TITLE
Wrong configure script argument to disable LTTng-UST support for LTTng-Tools profiles for 2.7 and before

### ISSUE THREAD

**Issue by frdeso** [eepp/vlttng#1]
The `--without-lttng-ust` option of the LTTng-Tools configure script was introduced in [commit a069e9a](https://github.com/lttng/lttng-tools/commit/a069e9a89a1fa25f38dfca485a297e9cb11962b2).
Before that, `--disable-lttng-ust` was used.

LTTng-Tools profiles with versions before 2.8 will fail if UST is not included.

**Comment by frdeso** [comment]
Should add a version check [here](https://github.com/eepp/vlttng/blob/master/vlttng/venv.py#L550)

**Comment by eepp** [comment]
> Should add a version check here

No. Simplest solution, and that's done in some distributions, is to pass both. `configure` will warn, but it works. Checking the version is much more error-prone (you can't rely on the branch/file name).

It's not like `--disable-lttng-ust` is ever going to mean something else in this configuration script anyway.

**Comment by frdeso** [comment]
Perfect! will do.

**Comment by eepp** [comment]
> Perfect! will do.

Boring but solid solution :wink:.
