### ISSUE TITLE
Support cross compilation for lttng

### ISSUE THREAD

**Issue by shrkamat** [eepp/vlttng#15]
It will be great if lttng can be cross compiled with this tool.

**Comment by eepp** [comment]
I believe it's a bit outside the scope of vlttng, but maybe you can already do it by setting the appropriate [`--build` and `--host` options](https://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html) with `vlttng`'s `--override` option? And possibly setting the `CC`/`CXX`/`LD` environment variables and so on before running `vlttng`?

**Comment by eepp** [comment]
Closing this since I never got feedback.
