### ISSUE TITLE
popt installation seems broken

### ISSUE THREAD

**Issue by yehuday** [eepp/vlttng#19]
Dear vlttng devs

trying to install popt through the vlttng tool fails since the TAR file on the rpm5 website seems to be in a bad state
or the wget command on my machine doesn't work properly 

i ran
`vlttng -p popt-1.16 lttng -j 48`
which outputs 
```
# Create LTTng virtual environment
mkdir -v -p /home/ec2-user/tools/lttng
mkdir -v -p /home/ec2-user/tools/lttng/home
mkdir -v -p /home/ec2-user/tools/lttng/usr/bin
mkdir -v -p /home/ec2-user/tools/lttng/usr/lib
mkdir -v -p /home/ec2-user/tools/lttng/usr/include
mkdir -v -p /home/ec2-user/tools/lttng/usr/opt
mkdir -v -p /home/ec2-user/tools/lttng/usr/share/java

Fetch sources
mkdir -v -p /home/ec2-user/tools/lttng/src
cd /home/ec2-user/tools/lttng/src
wget http://rpm5.org/files/popt/popt-1.16.tar.gz -O popt-1.16.tar.gz
mkdir -v -p /home/ec2-user/tools/lttng/src/popt
tar -xvf popt-1.16.tar.gz -C popt --strip-components=1
Error: Command exited with status 2
```

when i downloaded the popt tar file manually it was a HTML file, not a tar file. 
This happened also when i downloaded with a browser
in general it seems like the popt pages in rpm5 is broken as many of the other version files are missing (404)

is there a way to use the yum installed popt instead of installing popt in the environment ? 
i have popt 1.13 installed on my machine

**Comment by yehuday** [comment]
BTW - i am using vlttng v.0.10.7

**Comment by eepp** [comment]
Can confirm the `popt-1.16.tar.gz` file is not good anymore.

I'm going to use branches of [rpm-software-management/popt](https://github.com/rpm-software-management/popt) [like Arch does](https://archlinux.org/packages/core/x86_64/popt/) instead. It even seems like there's a popt 1.17 and 1.18 now!

In the meantime, you can omit the vlttng `popt` profile and it will use the popt of the system instead.

**Comment by yehuday** [comment]
thanks. turns out i had popt installed but not popt-devel which made the configure and build stage fail.
